# Generated by Django 4.1 on 2023-12-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito_vista', models.BooleanField(verbose_name='Crédito à vista')),
                ('credito_parcelado', models.BooleanField(verbose_name='Crédito parcelado')),
                ('debito', models.BooleanField(verbose_name='Débito')),
                ('pix', models.BooleanField(verbose_name='PIX')),
                ('cheque', models.BooleanField(verbose_name='Cheque')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['id'],
            },
        ),
    ]
