# Generated by Django 4.1 on 2023-12-07 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSocialnetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Item de Redes Social',
                'verbose_name_plural': 'Itens de Rede Social',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_socialnetwork',
            field=models.ManyToManyField(blank=True, through='clients.ClientSocialnetwork', to='socialnetworks.socialnetwork'),
        ),
        migrations.AddField(
            model_name='clientsocialnetwork',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientsocialnetwork',
            name='socialnetwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialnetworks.socialnetwork'),
        ),
    ]
