# Generated by Django 4.1 on 2023-12-13 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('motorista', '__first__'),
        ('loja', '__first__'),
        ('clients', '0001_initial'),
        ('veiculos', '__first__'),
        ('formapagamento', '0001_initial'),
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField()),
                ('hora_retirada', models.TimeField()),
                ('data_devolucao', models.DateField()),
                ('hora_devolucao', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteira.carteira')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.cliente')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapagamento.formapagamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.loja')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorista.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculo')),
            ],
        ),
    ]
